[workspace]
members = [
    "cosmic-panel-bin",
    "cosmic-panel-config",
    "xdg-shell-wrapper-config",
]
resolver = "3"

[profile.dev]
opt-level = 1

[workspace.package]
license = "GPL-3.0-only"

[profile.release]
lto = "thin"

[workspace.dependencies]
sctk = { package = "smithay-client-toolkit", version = "0.20.0", features = [
    "calloop",
    "xkbcommon",
] }
